---
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r libraries}

library(tidyverse)
library(magrittr)
# library(ggpubr)
# library(RColorBrewer)
library(colorspace)

```


```{r data, eval=FALSE}

(files <- 
  str_subset(str_subset(list.files("../results/tl1_X5_Y5/", full.names = TRUE), ".tar.gz", negate = TRUE), "asex"))
(files <- 
  str_subset(str_subset(list.files("../results/tl1_X5_Y5/", full.names = TRUE), ".tar.gz", negate = TRUE), "asex", negate = TRUE))
(files <- 
  str_subset(str_subset(list.files("../results/tl1_X5_Y5/", full.names = TRUE), ".tar.gz", negate = TRUE), "dens2"))


data_div <- NULL
data_shift <- NULL
for (f in files) {
  
  cat("processing file \n", "  ", f, "\n")
  
  data <- 
    read_delim(files[1], delim = ";") %>% 
    filter(time%%500==0)

  gc()

  data_div_alpha <-
    data %>% 
    # mutate(run = ordered(run)) %>% 
    filter(N > 0) %>% 
    group_by(grid_X, grid_Y, patches, nbr_species, CC, time_CC, pre_CC, post_CC, e_step_local, rep_type, m, mu, run, time, patch, X, Y, trophic_level) %>%
    # group_by(mu, run, time, patch, X, Y) %>% 
    mutate(p_N = N/sum(N),
           p_biomass = biomass/sum(biomass)) %>%
    summarise(alpha_H_N = -sum(p_N*log(p_N)),
              alpha_H_biomass = -sum(p_biomass*log(p_biomass))) %>% 
    ungroup() %>% 
    mutate(# alpha_div_N = exp(alpha_H_N),
      alpha_div_biomass = exp(alpha_H_biomass)) %>%
    group_by(grid_X, grid_Y, patches, nbr_species, CC, time_CC, pre_CC, post_CC, e_step_local, rep_type, m, mu, run, time, trophic_level) %>%
    # group_by(mu, run, time) %>% 
    summarise(alpha_div_N = exp((-1/n())*sum(-alpha_H_N)),
              alpha_div_biomass = exp((-1/n())*sum(-alpha_H_biomass)),
              alpha_H_N = mean(alpha_H_N),
              alpha_H_biomass = mean(alpha_H_biomass),
              # alpha_div_N = mean(alpha_div_N),
              # alpha_div_biomass = mean(alpha_div_biomass)
    ) %>% 
    ungroup()
  
  data_div_gamma <-
    data %>% 
    # mutate(run = ordered(run)) %>% 
    filter(N > 0) %>% 
    group_by(grid_X, grid_Y, patches, nbr_species, CC, time_CC, pre_CC, post_CC, e_step_local, rep_type, m, mu, run, time, species, trophic_level) %>%
    # group_by(mu, run, time, species) %>%
    summarise(N = sum(N),
              biomass = sum(biomass)) %>% 
    ungroup() %>% 
    group_by(grid_X, grid_Y, patches, nbr_species, CC, time_CC, pre_CC, post_CC, e_step_local, rep_type, m, mu, run, time, trophic_level) %>%
    # group_by(mu, run, time) %>%
    mutate(p_N = N/sum(N),
           p_biomass = biomass/sum(biomass)) %>%
    summarise(gamma_H_N = -sum(p_N*log(p_N)),
              gamma_H_biomass = -sum(p_biomass*log(p_biomass))) %>% 
    ungroup() %>% 
    mutate(gamma_div_N = exp(gamma_H_N),
           gamma_div_biomass = exp(gamma_H_biomass))
  
  
  data_div_join <-
    data_div_alpha %>% 
    left_join(data_div_gamma) %>% 
    mutate(beta_H_N = gamma_H_N-alpha_H_N,
           beta_H_biomass = gamma_H_biomass-alpha_H_biomass,
           beta_div_N = gamma_div_N/alpha_div_N,
           beta_div_biomass = gamma_div_biomass/alpha_div_biomass) %>% 
    select(-run) %>% 
    group_by(grid_X, grid_Y, patches, nbr_species, CC, time_CC, pre_CC, post_CC, e_step_local, rep_type, m, mu, time, trophic_level) %>%
    # group_by(mu, time) %>% 
    summarise(across(.fns = list(mean = ~mean(., na.rm = TRUE), var = ~var(., na.rm = TRUE)))) %>% 
    ungroup()
  
  data_div <-
    data_div %>% 
    bind_rows(data_div_join)

  rm(data_div_alpha, data_div_gamma, data_div_join)  
  gc()
  
  data_shift_f <-
    data %>% 
    # mutate(run = ordered(run)) %>% 
    filter(N > 0) %>% 
    mutate(X = as.numeric(as.character(X))) %>% 
    group_by(grid_X, grid_Y, patches, nbr_species, CC, time_CC, pre_CC, post_CC, e_step_local, rep_type, m, mu, run, time, species, trophic_level) %>%
    summarise(X_mean = mean(rep(X,N)),
              X_spread = sqrt(var(rep(X,N)))) %>% 
    ungroup() %>% 
    group_by(grid_X, grid_Y, patches, nbr_species, CC, time_CC, pre_CC, post_CC, e_step_local, rep_type, m, mu, run, species, trophic_level) %>%
    mutate(X_shift = abs(X_mean - X_mean[time == 0])) %>% 
    ungroup() %>% 
    group_by(grid_X, grid_Y, patches, nbr_species, CC, time_CC, pre_CC, post_CC, e_step_local, rep_type, m, mu, run, time, trophic_level) %>%
    summarise(X_spread = mean(X_spread),
              X_shift = mean(X_shift)) %>% 
    ungroup()
  
  data_shift <-
    data_shift %>% 
    bind_rows(
      data_shift_f %>% 
        group_by(grid_X, grid_Y, patches, nbr_species, CC, time_CC, pre_CC, post_CC, e_step_local, rep_type, m, mu, time, trophic_level) %>% 
        summarise(across(c(X_spread, X_shift), list(mean = ~mean(., na.rm = TRUE), var = ~var(., na.rm = TRUE)))) %>% 
        ungroup())

  rm(data, data_shift_f)  
  gc()

}

data_div_asex <- data_div
data_shift_asex <- data_shift
save(data_div_asex, data_shift_asex, file = "data_tl1_X5_Y5_asex.RData")

data_div_sex <- data_div
data_shift_sex <- data_shift
save(data_div_sex, data_shift_sex, file = "data_tl1_X5_Y5_sex.RData")

data_div_dens2 <- data_div
data_shift_dens2 <- data_shift
save(data_div_dens2, data_shift_dens2, file = "data_tl1_X5_Y5_dens2.RData")

rm(list = ls())
gc()

```


```{r load calculations}

load("data_tl1_X5_Y5_dens2.RData")

setting_dens2 <-
  data_div_dens2 %>% 
  distinct(CC, time_CC, nbr_species, e_step_local, rep_type, m, mu, trophic_level)


load("data_tl1_X5_Y5_asex.RData")
data_div_asex <- 
  data_div_asex %>% 
  filter(CC %in% unique(setting_dens2$CC),
         time_CC %in% unique(setting_dens2$time_CC),
         e_step_local %in% unique(setting_dens2$e_step_local),
         m %in% unique(setting_dens2$m),
         mu %in% unique(setting_dens2$mu)) %>% 
  mutate(grid_X = 5,
         grid_Y = 5,
         patches = 25,
         nbr_species = 25)

load("data_tl1_X5_Y5_sex.RData")
data_div_sex <- 
  data_div_sex %>% 
  filter(CC %in% unique(setting_dens2$CC),
         time_CC %in% unique(setting_dens2$time_CC),
         e_step_local %in% unique(setting_dens2$e_step_local),
         m %in% unique(setting_dens2$m),
         mu %in% unique(setting_dens2$mu)) %>% 
  mutate(grid_X = 5,
         grid_Y = 5,
         patches = 25,
         nbr_species = 25)

data_div <-
  data_div_dens2 %>% 
  bind_rows(data_div_asex) %>% 
  bind_rows(data_div_sex)


data_div <-
  data_div_asex %>% 
  bind_rows(data_div_sex)

data_shift <-
  data_shift_asex %>% 
  bind_rows(data_shift_sex)


```


```{r colors}

cbPalette <- c("#E69F00", # orange
               "#56B4E9", # lightblue
               "#009E73", # green
               "#F0E442", # yellow
               "#0072B2", # darkblue
               "#D55E00", # red
               "#CC79A7") # cyan

```


```{r figuren density}

for(r in levels(data$run)) {
  for(g_y in unique(data$grid_Y)) {
    for(tl in levels(data$trophic_level)) {
      for(mut in unique(data$mu)) {
        data %>% 
          filter(#time <= 1000,
            run == r,
            grid_Y == g_y,
            trophic_level == tl,
            mu == mut) %>%
          {ggplot(., aes(x = time)) +
              geom_line(aes(y = N, color = species), linetype = 1, size = 1) +
              scale_color_discrete_qualitative() +
              # scale_y_log10() +
              # facet_grid(Y ~ X, labeller = "label_both") +
              facet_grid(X ~ Y, labeller = "label_both") +
              ggtitle(str_c("Run ", r, "; trophic level ", tl, "; mu ", mut)) +
              guides(color = "none")} %>% 
          print()
      }
    }
  }
}

# figs_dens <-
#   data %>% 
#   group_by(run, trophic_level, mu) %>% 
#   nest() %>% 
#   transmute(fig = map(data, 
#                       ~{ggplot(., aes(x = time)) +
#                           geom_line(aes(y = N, color = species), linetype = 1, size = 1) +
#                           scale_color_discrete_qualitative() +
#                           facet_grid(X ~ Y, labeller = "label_both") +
#                           ggtitle(str_c("Run ", r, "; trophic level ", tl)) +
#                           guides(color = "none")}))
# 
# 
# map(figs_dens$fig, print)

```


```{r figuren div}

# for(st in unique(data_div_asex$e_step_local)) {
for(mg in unique(data_div$m)) {
  p <-
    data_div %>% 
    mutate(mu = ordered(mu, levels = c(1e-4, 0)),
           e_step_local = ordered(e_step_local),
           rep_type = ordered(rep_type)) %>% 
    filter(#time > 0,
           e_step_local == 0.001,
           m == mg) %>% 
    ggplot(aes(time, alpha_div_N_mean)) +
    geom_line(aes(color = rep_type, linetype = mu), size = 1) +
    geom_ribbon(aes(ymin = alpha_div_N_mean - 2*sqrt(alpha_div_N_var), 
                    ymax = alpha_div_N_mean + 2*sqrt(alpha_div_N_var), 
                    group = rep_type:mu,
                    fill = rep_type),
                alpha = 0.2) +
    scale_color_brewer(palette = "Dark2") +
    scale_fill_brewer(palette = "Dark2") +
    ggtitle(str_c("m = ", mg)) +
    facet_grid(CC ~ time_CC, labeller = "label_both") +
    theme_bw()
  print(p)
}
# }


for(mg in unique(data_div$m)) {
  p <-
    data_div %>% 
    mutate(mu = ordered(mu, levels = c(1e-4, 0)),
           e_step_local = ordered(e_step_local),
           rep_type = ordered(rep_type)) %>% 
    filter(time > 0,
           e_step_local == 0.001,
           m == mg) %>% 
    ggplot(aes(time, gamma_div_N_mean)) +
    geom_line(aes(color = rep_type, linetype = mu), size = 1) +
    geom_ribbon(aes(ymin = gamma_div_N_mean - 2*sqrt(gamma_div_N_var), 
                    ymax = gamma_div_N_mean + 2*sqrt(gamma_div_N_var), 
                    group = rep_type:mu,
                    fill = rep_type),
                alpha = 0.2) +
    scale_color_brewer(palette = "Dark2") +
    scale_fill_brewer(palette = "Dark2") +
    ggtitle(str_c("m = ", mg)) +
    facet_grid(CC ~ time_CC, labeller = "label_both") +
    theme_bw()
  print(p)
}


for(mg in unique(data_div$m)) {
  p <-
    data_div %>% 
    mutate(mu = ordered(mu, levels = c(1e-4, 0)),
           e_step_local = ordered(e_step_local),
           rep_type = ordered(rep_type)) %>% 
    filter(time > 0,
           e_step_local == 0.001,
           m == mg) %>% 
    ggplot(aes(time, beta_div_N_mean)) +
    geom_line(aes(color = rep_type, linetype = mu), size = 1) +
    geom_ribbon(aes(ymin = beta_div_N_mean - 2*sqrt(beta_div_N_var), 
                    ymax = beta_div_N_mean + 2*sqrt(beta_div_N_var), 
                    group = rep_type:mu,
                    fill = rep_type),
                alpha = 0.2) +
    scale_color_brewer(palette = "Dark2") +
    scale_fill_brewer(palette = "Dark2") +
    ggtitle(str_c("m = ", mg)) +
    facet_grid(CC ~ time_CC, labeller = "label_both") +
    theme_bw()
  print(p)
}


for(mg in unique(data_div_asex$m)) {
  p <-
    data_div_asex %>% 
    mutate(mu = ordered(mu),
           e_step_local = ordered(e_step_local)) %>% 
    filter(time == pre_CC,
           e_step_local == 0.001,
           m == mg) %>% 
    group_by(CC, time_CC, e_step_local, rep_type, m, trophic_level, time) %>% 
    summarise(alpha_div_ratio = alpha_div_N_mean[mu == 1e-4]/alpha_div_N_mean[mu == 0],
              beta_div_ratio = beta_div_N_mean[mu == 1e-4]/beta_div_N_mean[mu == 0],
              gamma_div_ratio = gamma_div_N_mean[mu == 1e-4]/gamma_div_N_mean[mu == 0]) %>% 
    ungroup() %>% 
    pivot_longer(cols = contains("div_ratio"),
                 names_to = "level",
                 values_to = "div_ratio") %>% 
    mutate(level = str_remove(level, "_div_ratio")) %>% 
    ggplot(aes(level, div_ratio)) +
    geom_col(aes(fill = level)) +
    scale_y_log10() +
    scale_color_brewer(palette = "Dark2") +
    scale_fill_brewer(palette = "Dark2") +
    ggtitle(str_c("m = ", mg)) +
    facet_grid(CC ~ time_CC, labeller = "label_both") +
    theme_bw()
  print(p)
}


for(mg in unique(data_div_asex$m)) {
  p <-
    data_div_asex %>% 
    mutate(mu = ordered(mu),
           e_step_local = ordered(e_step_local)) %>% 
    filter(time == pre_CC + time_CC + post_CC,
           e_step_local == 0.001,
           m == mg) %>% 
    group_by(CC, time_CC, e_step_local, rep_type, m, trophic_level) %>% 
    summarise(alpha_div_ratio = alpha_div_N_mean[mu == 1e-4]/alpha_div_N_mean[mu == 0],
              beta_div_ratio = beta_div_N_mean[mu == 1e-4]/beta_div_N_mean[mu == 0],
              gamma_div_ratio = gamma_div_N_mean[mu == 1e-4]/gamma_div_N_mean[mu == 0]) %>% 
    ungroup() %>% 
    pivot_longer(cols = contains("div_ratio"),
                 names_to = "level",
                 values_to = "div_ratio") %>% 
    mutate(level = str_remove(level, "_div_ratio")) %>% 
    ggplot(aes(level, div_ratio)) +
    geom_col(aes(fill = level)) +
    scale_y_log10() +
    scale_color_brewer(palette = "Dark2") +
    scale_fill_brewer(palette = "Dark2") +
    ggtitle(str_c("m = ", mg)) +
    facet_grid(CC ~ time_CC, labeller = "label_both") +
    theme_bw()
  print(p)
}


for(mg in unique(data_div_asex$m)) {
  p <-
    data_div_asex %>% 
    mutate(mu = ordered(mu),
           e_step_local = ordered(e_step_local),
           total_time = pre_CC + time_CC + post_CC) %>% 
    filter(time == pre_CC | time == total_time,
           e_step_local == 0.001,
           m == mg) %>% 
    mutate(time = ifelse(time == pre_CC, "pre_CC", "end"),
           time = factor(time, levels = c("pre_CC", "end"))) %>% 
    group_by(CC, time_CC, e_step_local, rep_type, m, trophic_level, time) %>% 
    summarise(alpha_div_ratio = alpha_div_N_mean[mu == 1e-4]/alpha_div_N_mean[mu == 0],
              beta_div_ratio = beta_div_N_mean[mu == 1e-4]/beta_div_N_mean[mu == 0],
              gamma_div_ratio = gamma_div_N_mean[mu == 1e-4]/gamma_div_N_mean[mu == 0]) %>% 
    ungroup() %>% 
    pivot_longer(cols = contains("div_ratio"),
                 names_to = "level",
                 values_to = "div_ratio") %>% 
    mutate(level = str_remove(level, "_div_ratio")) %>% 
    ggplot(aes(level, div_ratio)) +
    geom_col(aes(fill = ordered(time)), position = "dodge") +
    scale_y_log10() +
    scale_color_brewer(palette = "Dark2") +
    scale_fill_brewer(palette = "Dark2") +
    ggtitle(str_c("m = ", mg)) +
    facet_grid(CC ~ time_CC, labeller = "label_both") +
    theme_bw()
  print(p)
}


for(mg in unique(data_div_asex$m)) {
  p <-
    data_div_asex %>% 
    mutate(mu = ordered(mu),
           e_step_local = ordered(e_step_local),
           total_time = pre_CC + time_CC + post_CC) %>% 
    filter(time == pre_CC | time == total_time,
           e_step_local == 0.001,
           m == mg) %>% 
    group_by(CC, time_CC, e_step_local, rep_type, mu, m, trophic_level) %>% 
    summarise(alpha_div_ratio = alpha_div_N_mean[time == total_time]/alpha_div_N_mean[time == pre_CC],
              beta_div_ratio = beta_div_N_mean[time == total_time]/beta_div_N_mean[time == pre_CC],
              gamma_div_ratio = gamma_div_N_mean[time == total_time]/gamma_div_N_mean[time == pre_CC]) %>% 
    ungroup() %>% 
    pivot_longer(cols = contains("div_ratio"),
                 names_to = "level",
                 values_to = "div_ratio") %>% 
    mutate(level = str_remove(level, "_div_ratio")) %>% 
    ggplot(aes(level, div_ratio)) +
    geom_col(aes(fill = mu), position = "dodge") +
    scale_y_log10() +
    scale_color_brewer(palette = "Dark2") +
    scale_fill_brewer(palette = "Dark2") +
    ggtitle(str_c("m = ", mg)) +
    facet_grid(CC ~ time_CC, labeller = "label_both") +
    theme_bw()
  print(p)
}


data_div %>% 
  select(trophic_level, mu, time, contains("div_N")) %>% 
  pivot_longer(cols = contains("div_N"),
               names_to = "level",
               values_to = "div_N") %>% 
  mutate(level = str_remove(level, "_div_N")) %>% 
  ggplot(aes(time, div_N, color = level)) +
  geom_line(aes(linetype = level), size = 1) +
  facet_grid(trophic_level ~ mu, labeller = "label_both")

data_div %>% 
  select(trophic_level, mu, time, contains("div_N")) %>% 
  filter(time == 11000) %>% 
  pivot_longer(cols = contains("div_N"),
               names_to = "level",
               values_to = "div_N") %>% 
  mutate(level = str_remove(level, "_div_N")) %>% 
  ggplot(aes(trophic_level, div_N, fill = trophic_level)) +
  geom_col() +
  facet_grid(mu ~ level, labeller = "label_both") +
  scale_x_discrete(labels = NULL)

data_div %>% 
  select(trophic_level, grid_Y, mu, time, contains("div_N")) %>% 
  # filter(time == 11000) %>% 
  filter(time == max(time)) %>%
  # filter(time == 5000 | time == max(time)) %>% 
  pivot_longer(cols = contains("div_N"),
               names_to = "level",
               values_to = "div_N") %>% 
  mutate(level = str_remove(level, "_div_N"),
         time = ordered(time)) %>% 
  ggplot(aes(time, div_N, fill = mu)) +
  geom_col(position = "dodge") +
  # scale_y_log10() +
  facet_grid(level ~ trophic_level + grid_Y, labeller = "label_both", scales = "free_y") +
  scale_x_discrete(labels = NULL)

```


```{r figuren shift & spread}

for(mg in unique(data_div$m)) {
  p <-
    data_shift %>% 
    mutate(mu = ordered(mu, levels = c(1e-4, 0)),
           e_step_local = ordered(e_step_local),
           rep_type = ordered(rep_type)) %>% 
    filter(#time > 0,
           e_step_local == 0.002,
           m == mg) %>% 
    ggplot(aes(time, X_shift_mean)) +
    geom_line(aes(color = rep_type, linetype = mu), size = 1) +
    geom_ribbon(aes(ymin = X_shift_mean - 2*sqrt(X_shift_var), 
                    ymax = X_shift_mean + 2*sqrt(X_shift_var), 
                    group = rep_type:mu,
                    fill = rep_type),
                alpha = 0.2) +
    scale_color_brewer(palette = "Dark2") +
    scale_fill_brewer(palette = "Dark2") +
    ggtitle(str_c("m = ", mg)) +
    facet_grid(CC ~ time_CC, labeller = "label_both") +
    theme_bw()
  print(p)
}


for(mg in unique(data_div_asex$m)) {
  p <-
    data_shift_asex %>% 
    mutate(mu = ordered(mu),
           e_step_local = ordered(e_step_local)) %>% 
    filter(#time > 0,
           e_step_local == 0.001,
           m == mg) %>% 
    ggplot(aes(time, X_spread_mean)) +
    geom_line(aes(color = mu, linetype = e_step_local), size = 1) +
    geom_ribbon(aes(ymin = X_spread_mean - 2*sqrt(X_spread_var), 
                    ymax = X_spread_mean + 2*sqrt(X_spread_var), 
                    fill = mu),
                alpha = 0.2) +
    scale_color_brewer(palette = "Dark2") +
    scale_fill_brewer(palette = "Dark2") +
    ggtitle(str_c("m = ", mg)) +
    facet_grid(CC ~ time_CC, labeller = "label_both") +
    theme_bw()
  print(p)
}


```


```{r aantal soorten}

for(rep in unique(data_div$rep_type)) {
  p <-
    data_div %>% 
    mutate(mu = ordered(mu),
           e_step_local = ordered(e_step_local),
           nbr_species = ordered(nbr_species)) %>% 
    filter(#time > 0,
           e_step_local == 0.001,
           rep_type == rep) %>% 
    ggplot(aes(time, alpha_div_N_mean)) +
    geom_line(aes(color = nbr_species, linetype = mu), size = 1) +
    geom_ribbon(aes(ymin = alpha_div_N_mean - 2*sqrt(alpha_div_N_var), 
                    ymax = alpha_div_N_mean + 2*sqrt(alpha_div_N_var), 
                    group = nbr_species:mu,
                    fill = nbr_species),
                alpha = 0.2) +
    scale_color_brewer(palette = "Dark2") +
    scale_fill_brewer(palette = "Dark2") +
    ggtitle(str_c("rep = ", rep)) +
    facet_grid(CC ~ time_CC, labeller = "label_both") +
    theme_bw()
  print(p)
}

for(rep in unique(data_div$rep_type)) {
  p <-
    data_div %>% 
    mutate(mu = ordered(mu),
           e_step_local = ordered(e_step_local),
           nbr_species = ordered(nbr_species)) %>% 
    filter(#time > 0,
           e_step_local == 0.001,
           rep_type == rep) %>% 
    ggplot(aes(time, gamma_div_N_mean)) +
    geom_line(aes(color = nbr_species, linetype = mu), size = 1) +
    geom_ribbon(aes(ymin = gamma_div_N_mean - 2*sqrt(gamma_div_N_var), 
                    ymax = gamma_div_N_mean + 2*sqrt(gamma_div_N_var), 
                    group = nbr_species:mu,
                    fill = nbr_species),
                alpha = 0.2) +
    scale_color_brewer(palette = "Dark2") +
    scale_fill_brewer(palette = "Dark2") +
    ggtitle(str_c("rep = ", rep)) +
    facet_grid(CC ~ time_CC, labeller = "label_both") +
    theme_bw()
  print(p)
}

for(rep in unique(data_div$rep_type)) {
  p <-
    data_div %>% 
    mutate(mu = ordered(mu),
           e_step_local = ordered(e_step_local),
           nbr_species = ordered(nbr_species)) %>% 
    filter(#time > 0,
           e_step_local == 0.001,
           rep_type == rep) %>% 
    ggplot(aes(time, beta_div_N_mean)) +
    geom_line(aes(color = nbr_species, linetype = mu), size = 1) +
    geom_ribbon(aes(ymin = beta_div_N_mean - 2*sqrt(beta_div_N_var), 
                    ymax = beta_div_N_mean + 2*sqrt(beta_div_N_var), 
                    group = nbr_species:mu,
                    fill = nbr_species),
                alpha = 0.2) +
    scale_color_brewer(palette = "Dark2") +
    scale_fill_brewer(palette = "Dark2") +
    ggtitle(str_c("rep = ", rep)) +
    facet_grid(CC ~ time_CC, labeller = "label_both") +
    theme_bw()
  print(p)
}

```

